/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OtaSessionLoginRouteImport } from './routes/ota-session-login'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppShiftsRouteImport } from './routes/app/shifts'
import { Route as AppAppRouteImport } from './routes/app/_app'
import { Route as AppShiftsIndexRouteImport } from './routes/app/shifts/index'
import { Route as AppAppIndexRouteImport } from './routes/app/_app/index'
import { Route as AppShiftsShiftTypesRouteImport } from './routes/app/shifts/shift-types'
import { Route as AppShiftsShiftSchedulesRouteImport } from './routes/app/shifts/shift-schedules'
import { Route as AppShiftsSchedulingRouteImport } from './routes/app/shifts/scheduling'
import { Route as AppShiftsReportsRouteImport } from './routes/app/shifts/reports'
import { Route as AppShiftsPeriodExceptionsRouteImport } from './routes/app/shifts/period-exceptions'
import { Route as AppShiftsPeriodDetailsRouteImport } from './routes/app/shifts/period-details'
import { Route as AppShiftsMyShiftsRouteImport } from './routes/app/shifts/my-shifts'
import { Route as AppShiftsManageUsersRouteImport } from './routes/app/shifts/manage-users'
import { Route as AppShiftsAttendanceRouteImport } from './routes/app/shifts/attendance'
import { Route as AppAppUsersRouteImport } from './routes/app/_app/users'
import { Route as AppAppSuspensionsRouteImport } from './routes/app/_app/suspensions'
import { Route as AppAppSessionsRouteImport } from './routes/app/_app/sessions'
import { Route as AppAppRolesRouteImport } from './routes/app/_app/roles'
import { Route as AppAppMySessionsRouteImport } from './routes/app/_app/my-sessions'
import { Route as AppAppMyAgreementsRouteImport } from './routes/app/_app/my-agreements'
import { Route as AppAppKiosksRouteImport } from './routes/app/_app/kiosks'
import { Route as AppAppConfigurationRouteImport } from './routes/app/_app/configuration'
import { Route as AppAppAuditLogsRouteImport } from './routes/app/_app/audit-logs'
import { Route as AppAppApiTokensRouteImport } from './routes/app/_app/api-tokens'
import { Route as AppAppAgreementsRouteImport } from './routes/app/_app/agreements'

const OtaSessionLoginRoute = OtaSessionLoginRouteImport.update({
  id: '/ota-session-login',
  path: '/ota-session-login',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppShiftsRoute = AppShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AppRoute,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/_app',
  getParentRoute: () => AppRoute,
} as any)
const AppShiftsIndexRoute = AppShiftsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppShiftsRoute,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppRoute,
} as any)
const AppShiftsShiftTypesRoute = AppShiftsShiftTypesRouteImport.update({
  id: '/shift-types',
  path: '/shift-types',
  getParentRoute: () => AppShiftsRoute,
} as any)
const AppShiftsShiftSchedulesRoute = AppShiftsShiftSchedulesRouteImport.update({
  id: '/shift-schedules',
  path: '/shift-schedules',
  getParentRoute: () => AppShiftsRoute,
} as any)
const AppShiftsSchedulingRoute = AppShiftsSchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => AppShiftsRoute,
} as any)
const AppShiftsReportsRoute = AppShiftsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppShiftsRoute,
} as any)
const AppShiftsPeriodExceptionsRoute =
  AppShiftsPeriodExceptionsRouteImport.update({
    id: '/period-exceptions',
    path: '/period-exceptions',
    getParentRoute: () => AppShiftsRoute,
  } as any)
const AppShiftsPeriodDetailsRoute = AppShiftsPeriodDetailsRouteImport.update({
  id: '/period-details',
  path: '/period-details',
  getParentRoute: () => AppShiftsRoute,
} as any)
const AppShiftsMyShiftsRoute = AppShiftsMyShiftsRouteImport.update({
  id: '/my-shifts',
  path: '/my-shifts',
  getParentRoute: () => AppShiftsRoute,
} as any)
const AppShiftsManageUsersRoute = AppShiftsManageUsersRouteImport.update({
  id: '/manage-users',
  path: '/manage-users',
  getParentRoute: () => AppShiftsRoute,
} as any)
const AppShiftsAttendanceRoute = AppShiftsAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppShiftsRoute,
} as any)
const AppAppUsersRoute = AppAppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppSuspensionsRoute = AppAppSuspensionsRouteImport.update({
  id: '/suspensions',
  path: '/suspensions',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppSessionsRoute = AppAppSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppRolesRoute = AppAppRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppMySessionsRoute = AppAppMySessionsRouteImport.update({
  id: '/my-sessions',
  path: '/my-sessions',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppMyAgreementsRoute = AppAppMyAgreementsRouteImport.update({
  id: '/my-agreements',
  path: '/my-agreements',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppKiosksRoute = AppAppKiosksRouteImport.update({
  id: '/kiosks',
  path: '/kiosks',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppConfigurationRoute = AppAppConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppAuditLogsRoute = AppAppAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppApiTokensRoute = AppAppApiTokensRouteImport.update({
  id: '/api-tokens',
  path: '/api-tokens',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppAgreementsRoute = AppAppAgreementsRouteImport.update({
  id: '/agreements',
  path: '/agreements',
  getParentRoute: () => AppAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppAppRouteWithChildren
  '/login': typeof LoginRoute
  '/ota-session-login': typeof OtaSessionLoginRoute
  '/app/shifts': typeof AppShiftsRouteWithChildren
  '/app/agreements': typeof AppAppAgreementsRoute
  '/app/api-tokens': typeof AppAppApiTokensRoute
  '/app/audit-logs': typeof AppAppAuditLogsRoute
  '/app/configuration': typeof AppAppConfigurationRoute
  '/app/kiosks': typeof AppAppKiosksRoute
  '/app/my-agreements': typeof AppAppMyAgreementsRoute
  '/app/my-sessions': typeof AppAppMySessionsRoute
  '/app/roles': typeof AppAppRolesRoute
  '/app/sessions': typeof AppAppSessionsRoute
  '/app/suspensions': typeof AppAppSuspensionsRoute
  '/app/users': typeof AppAppUsersRoute
  '/app/shifts/attendance': typeof AppShiftsAttendanceRoute
  '/app/shifts/manage-users': typeof AppShiftsManageUsersRoute
  '/app/shifts/my-shifts': typeof AppShiftsMyShiftsRoute
  '/app/shifts/period-details': typeof AppShiftsPeriodDetailsRoute
  '/app/shifts/period-exceptions': typeof AppShiftsPeriodExceptionsRoute
  '/app/shifts/reports': typeof AppShiftsReportsRoute
  '/app/shifts/scheduling': typeof AppShiftsSchedulingRoute
  '/app/shifts/shift-schedules': typeof AppShiftsShiftSchedulesRoute
  '/app/shifts/shift-types': typeof AppShiftsShiftTypesRoute
  '/app/': typeof AppAppIndexRoute
  '/app/shifts/': typeof AppShiftsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppAppIndexRoute
  '/login': typeof LoginRoute
  '/ota-session-login': typeof OtaSessionLoginRoute
  '/app/agreements': typeof AppAppAgreementsRoute
  '/app/api-tokens': typeof AppAppApiTokensRoute
  '/app/audit-logs': typeof AppAppAuditLogsRoute
  '/app/configuration': typeof AppAppConfigurationRoute
  '/app/kiosks': typeof AppAppKiosksRoute
  '/app/my-agreements': typeof AppAppMyAgreementsRoute
  '/app/my-sessions': typeof AppAppMySessionsRoute
  '/app/roles': typeof AppAppRolesRoute
  '/app/sessions': typeof AppAppSessionsRoute
  '/app/suspensions': typeof AppAppSuspensionsRoute
  '/app/users': typeof AppAppUsersRoute
  '/app/shifts/attendance': typeof AppShiftsAttendanceRoute
  '/app/shifts/manage-users': typeof AppShiftsManageUsersRoute
  '/app/shifts/my-shifts': typeof AppShiftsMyShiftsRoute
  '/app/shifts/period-details': typeof AppShiftsPeriodDetailsRoute
  '/app/shifts/period-exceptions': typeof AppShiftsPeriodExceptionsRoute
  '/app/shifts/reports': typeof AppShiftsReportsRoute
  '/app/shifts/scheduling': typeof AppShiftsSchedulingRoute
  '/app/shifts/shift-schedules': typeof AppShiftsShiftSchedulesRoute
  '/app/shifts/shift-types': typeof AppShiftsShiftTypesRoute
  '/app/shifts': typeof AppShiftsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/ota-session-login': typeof OtaSessionLoginRoute
  '/app/_app': typeof AppAppRouteWithChildren
  '/app/shifts': typeof AppShiftsRouteWithChildren
  '/app/_app/agreements': typeof AppAppAgreementsRoute
  '/app/_app/api-tokens': typeof AppAppApiTokensRoute
  '/app/_app/audit-logs': typeof AppAppAuditLogsRoute
  '/app/_app/configuration': typeof AppAppConfigurationRoute
  '/app/_app/kiosks': typeof AppAppKiosksRoute
  '/app/_app/my-agreements': typeof AppAppMyAgreementsRoute
  '/app/_app/my-sessions': typeof AppAppMySessionsRoute
  '/app/_app/roles': typeof AppAppRolesRoute
  '/app/_app/sessions': typeof AppAppSessionsRoute
  '/app/_app/suspensions': typeof AppAppSuspensionsRoute
  '/app/_app/users': typeof AppAppUsersRoute
  '/app/shifts/attendance': typeof AppShiftsAttendanceRoute
  '/app/shifts/manage-users': typeof AppShiftsManageUsersRoute
  '/app/shifts/my-shifts': typeof AppShiftsMyShiftsRoute
  '/app/shifts/period-details': typeof AppShiftsPeriodDetailsRoute
  '/app/shifts/period-exceptions': typeof AppShiftsPeriodExceptionsRoute
  '/app/shifts/reports': typeof AppShiftsReportsRoute
  '/app/shifts/scheduling': typeof AppShiftsSchedulingRoute
  '/app/shifts/shift-schedules': typeof AppShiftsShiftSchedulesRoute
  '/app/shifts/shift-types': typeof AppShiftsShiftTypesRoute
  '/app/_app/': typeof AppAppIndexRoute
  '/app/shifts/': typeof AppShiftsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/ota-session-login'
    | '/app/shifts'
    | '/app/agreements'
    | '/app/api-tokens'
    | '/app/audit-logs'
    | '/app/configuration'
    | '/app/kiosks'
    | '/app/my-agreements'
    | '/app/my-sessions'
    | '/app/roles'
    | '/app/sessions'
    | '/app/suspensions'
    | '/app/users'
    | '/app/shifts/attendance'
    | '/app/shifts/manage-users'
    | '/app/shifts/my-shifts'
    | '/app/shifts/period-details'
    | '/app/shifts/period-exceptions'
    | '/app/shifts/reports'
    | '/app/shifts/scheduling'
    | '/app/shifts/shift-schedules'
    | '/app/shifts/shift-types'
    | '/app/'
    | '/app/shifts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/ota-session-login'
    | '/app/agreements'
    | '/app/api-tokens'
    | '/app/audit-logs'
    | '/app/configuration'
    | '/app/kiosks'
    | '/app/my-agreements'
    | '/app/my-sessions'
    | '/app/roles'
    | '/app/sessions'
    | '/app/suspensions'
    | '/app/users'
    | '/app/shifts/attendance'
    | '/app/shifts/manage-users'
    | '/app/shifts/my-shifts'
    | '/app/shifts/period-details'
    | '/app/shifts/period-exceptions'
    | '/app/shifts/reports'
    | '/app/shifts/scheduling'
    | '/app/shifts/shift-schedules'
    | '/app/shifts/shift-types'
    | '/app/shifts'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/ota-session-login'
    | '/app/_app'
    | '/app/shifts'
    | '/app/_app/agreements'
    | '/app/_app/api-tokens'
    | '/app/_app/audit-logs'
    | '/app/_app/configuration'
    | '/app/_app/kiosks'
    | '/app/_app/my-agreements'
    | '/app/_app/my-sessions'
    | '/app/_app/roles'
    | '/app/_app/sessions'
    | '/app/_app/suspensions'
    | '/app/_app/users'
    | '/app/shifts/attendance'
    | '/app/shifts/manage-users'
    | '/app/shifts/my-shifts'
    | '/app/shifts/period-details'
    | '/app/shifts/period-exceptions'
    | '/app/shifts/reports'
    | '/app/shifts/scheduling'
    | '/app/shifts/shift-schedules'
    | '/app/shifts/shift-types'
    | '/app/_app/'
    | '/app/shifts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OtaSessionLoginRoute: typeof OtaSessionLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ota-session-login': {
      id: '/ota-session-login'
      path: '/ota-session-login'
      fullPath: '/ota-session-login'
      preLoaderRoute: typeof OtaSessionLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/shifts': {
      id: '/app/shifts'
      path: '/shifts'
      fullPath: '/app/shifts'
      preLoaderRoute: typeof AppShiftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/_app': {
      id: '/app/_app'
      path: ''
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shifts/': {
      id: '/app/shifts/'
      path: '/'
      fullPath: '/app/shifts/'
      preLoaderRoute: typeof AppShiftsIndexRouteImport
      parentRoute: typeof AppShiftsRoute
    }
    '/app/_app/': {
      id: '/app/_app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/shifts/shift-types': {
      id: '/app/shifts/shift-types'
      path: '/shift-types'
      fullPath: '/app/shifts/shift-types'
      preLoaderRoute: typeof AppShiftsShiftTypesRouteImport
      parentRoute: typeof AppShiftsRoute
    }
    '/app/shifts/shift-schedules': {
      id: '/app/shifts/shift-schedules'
      path: '/shift-schedules'
      fullPath: '/app/shifts/shift-schedules'
      preLoaderRoute: typeof AppShiftsShiftSchedulesRouteImport
      parentRoute: typeof AppShiftsRoute
    }
    '/app/shifts/scheduling': {
      id: '/app/shifts/scheduling'
      path: '/scheduling'
      fullPath: '/app/shifts/scheduling'
      preLoaderRoute: typeof AppShiftsSchedulingRouteImport
      parentRoute: typeof AppShiftsRoute
    }
    '/app/shifts/reports': {
      id: '/app/shifts/reports'
      path: '/reports'
      fullPath: '/app/shifts/reports'
      preLoaderRoute: typeof AppShiftsReportsRouteImport
      parentRoute: typeof AppShiftsRoute
    }
    '/app/shifts/period-exceptions': {
      id: '/app/shifts/period-exceptions'
      path: '/period-exceptions'
      fullPath: '/app/shifts/period-exceptions'
      preLoaderRoute: typeof AppShiftsPeriodExceptionsRouteImport
      parentRoute: typeof AppShiftsRoute
    }
    '/app/shifts/period-details': {
      id: '/app/shifts/period-details'
      path: '/period-details'
      fullPath: '/app/shifts/period-details'
      preLoaderRoute: typeof AppShiftsPeriodDetailsRouteImport
      parentRoute: typeof AppShiftsRoute
    }
    '/app/shifts/my-shifts': {
      id: '/app/shifts/my-shifts'
      path: '/my-shifts'
      fullPath: '/app/shifts/my-shifts'
      preLoaderRoute: typeof AppShiftsMyShiftsRouteImport
      parentRoute: typeof AppShiftsRoute
    }
    '/app/shifts/manage-users': {
      id: '/app/shifts/manage-users'
      path: '/manage-users'
      fullPath: '/app/shifts/manage-users'
      preLoaderRoute: typeof AppShiftsManageUsersRouteImport
      parentRoute: typeof AppShiftsRoute
    }
    '/app/shifts/attendance': {
      id: '/app/shifts/attendance'
      path: '/attendance'
      fullPath: '/app/shifts/attendance'
      preLoaderRoute: typeof AppShiftsAttendanceRouteImport
      parentRoute: typeof AppShiftsRoute
    }
    '/app/_app/users': {
      id: '/app/_app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppAppUsersRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/suspensions': {
      id: '/app/_app/suspensions'
      path: '/suspensions'
      fullPath: '/app/suspensions'
      preLoaderRoute: typeof AppAppSuspensionsRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/sessions': {
      id: '/app/_app/sessions'
      path: '/sessions'
      fullPath: '/app/sessions'
      preLoaderRoute: typeof AppAppSessionsRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/roles': {
      id: '/app/_app/roles'
      path: '/roles'
      fullPath: '/app/roles'
      preLoaderRoute: typeof AppAppRolesRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/my-sessions': {
      id: '/app/_app/my-sessions'
      path: '/my-sessions'
      fullPath: '/app/my-sessions'
      preLoaderRoute: typeof AppAppMySessionsRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/my-agreements': {
      id: '/app/_app/my-agreements'
      path: '/my-agreements'
      fullPath: '/app/my-agreements'
      preLoaderRoute: typeof AppAppMyAgreementsRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/kiosks': {
      id: '/app/_app/kiosks'
      path: '/kiosks'
      fullPath: '/app/kiosks'
      preLoaderRoute: typeof AppAppKiosksRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/configuration': {
      id: '/app/_app/configuration'
      path: '/configuration'
      fullPath: '/app/configuration'
      preLoaderRoute: typeof AppAppConfigurationRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/audit-logs': {
      id: '/app/_app/audit-logs'
      path: '/audit-logs'
      fullPath: '/app/audit-logs'
      preLoaderRoute: typeof AppAppAuditLogsRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/api-tokens': {
      id: '/app/_app/api-tokens'
      path: '/api-tokens'
      fullPath: '/app/api-tokens'
      preLoaderRoute: typeof AppAppApiTokensRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/agreements': {
      id: '/app/_app/agreements'
      path: '/agreements'
      fullPath: '/app/agreements'
      preLoaderRoute: typeof AppAppAgreementsRouteImport
      parentRoute: typeof AppAppRoute
    }
  }
}

interface AppAppRouteChildren {
  AppAppAgreementsRoute: typeof AppAppAgreementsRoute
  AppAppApiTokensRoute: typeof AppAppApiTokensRoute
  AppAppAuditLogsRoute: typeof AppAppAuditLogsRoute
  AppAppConfigurationRoute: typeof AppAppConfigurationRoute
  AppAppKiosksRoute: typeof AppAppKiosksRoute
  AppAppMyAgreementsRoute: typeof AppAppMyAgreementsRoute
  AppAppMySessionsRoute: typeof AppAppMySessionsRoute
  AppAppRolesRoute: typeof AppAppRolesRoute
  AppAppSessionsRoute: typeof AppAppSessionsRoute
  AppAppSuspensionsRoute: typeof AppAppSuspensionsRoute
  AppAppUsersRoute: typeof AppAppUsersRoute
  AppAppIndexRoute: typeof AppAppIndexRoute
}

const AppAppRouteChildren: AppAppRouteChildren = {
  AppAppAgreementsRoute: AppAppAgreementsRoute,
  AppAppApiTokensRoute: AppAppApiTokensRoute,
  AppAppAuditLogsRoute: AppAppAuditLogsRoute,
  AppAppConfigurationRoute: AppAppConfigurationRoute,
  AppAppKiosksRoute: AppAppKiosksRoute,
  AppAppMyAgreementsRoute: AppAppMyAgreementsRoute,
  AppAppMySessionsRoute: AppAppMySessionsRoute,
  AppAppRolesRoute: AppAppRolesRoute,
  AppAppSessionsRoute: AppAppSessionsRoute,
  AppAppSuspensionsRoute: AppAppSuspensionsRoute,
  AppAppUsersRoute: AppAppUsersRoute,
  AppAppIndexRoute: AppAppIndexRoute,
}

const AppAppRouteWithChildren =
  AppAppRoute._addFileChildren(AppAppRouteChildren)

interface AppShiftsRouteChildren {
  AppShiftsAttendanceRoute: typeof AppShiftsAttendanceRoute
  AppShiftsManageUsersRoute: typeof AppShiftsManageUsersRoute
  AppShiftsMyShiftsRoute: typeof AppShiftsMyShiftsRoute
  AppShiftsPeriodDetailsRoute: typeof AppShiftsPeriodDetailsRoute
  AppShiftsPeriodExceptionsRoute: typeof AppShiftsPeriodExceptionsRoute
  AppShiftsReportsRoute: typeof AppShiftsReportsRoute
  AppShiftsSchedulingRoute: typeof AppShiftsSchedulingRoute
  AppShiftsShiftSchedulesRoute: typeof AppShiftsShiftSchedulesRoute
  AppShiftsShiftTypesRoute: typeof AppShiftsShiftTypesRoute
  AppShiftsIndexRoute: typeof AppShiftsIndexRoute
}

const AppShiftsRouteChildren: AppShiftsRouteChildren = {
  AppShiftsAttendanceRoute: AppShiftsAttendanceRoute,
  AppShiftsManageUsersRoute: AppShiftsManageUsersRoute,
  AppShiftsMyShiftsRoute: AppShiftsMyShiftsRoute,
  AppShiftsPeriodDetailsRoute: AppShiftsPeriodDetailsRoute,
  AppShiftsPeriodExceptionsRoute: AppShiftsPeriodExceptionsRoute,
  AppShiftsReportsRoute: AppShiftsReportsRoute,
  AppShiftsSchedulingRoute: AppShiftsSchedulingRoute,
  AppShiftsShiftSchedulesRoute: AppShiftsShiftSchedulesRoute,
  AppShiftsShiftTypesRoute: AppShiftsShiftTypesRoute,
  AppShiftsIndexRoute: AppShiftsIndexRoute,
}

const AppShiftsRouteWithChildren = AppShiftsRoute._addFileChildren(
  AppShiftsRouteChildren,
)

interface AppRouteChildren {
  AppAppRoute: typeof AppAppRouteWithChildren
  AppShiftsRoute: typeof AppShiftsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAppRoute: AppAppRouteWithChildren,
  AppShiftsRoute: AppShiftsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OtaSessionLoginRoute: OtaSessionLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
