/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OverviewRouteImport } from './routes/_overview'
import { Route as OverviewIndexRouteImport } from './routes/_overview/index'
import { Route as OverviewStaffingRouteImport } from './routes/_overview/staffing'
import { Route as OverviewEquipmentRouteImport } from './routes/_overview/equipment'

const OverviewRoute = OverviewRouteImport.update({
  id: '/_overview',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewIndexRoute = OverviewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OverviewRoute,
} as any)
const OverviewStaffingRoute = OverviewStaffingRouteImport.update({
  id: '/staffing',
  path: '/staffing',
  getParentRoute: () => OverviewRoute,
} as any)
const OverviewEquipmentRoute = OverviewEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => OverviewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof OverviewIndexRoute
  '/equipment': typeof OverviewEquipmentRoute
  '/staffing': typeof OverviewStaffingRoute
}
export interface FileRoutesByTo {
  '/equipment': typeof OverviewEquipmentRoute
  '/staffing': typeof OverviewStaffingRoute
  '/': typeof OverviewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_overview': typeof OverviewRouteWithChildren
  '/_overview/equipment': typeof OverviewEquipmentRoute
  '/_overview/staffing': typeof OverviewStaffingRoute
  '/_overview/': typeof OverviewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/equipment' | '/staffing'
  fileRoutesByTo: FileRoutesByTo
  to: '/equipment' | '/staffing' | '/'
  id:
    | '__root__'
    | '/_overview'
    | '/_overview/equipment'
    | '/_overview/staffing'
    | '/_overview/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  OverviewRoute: typeof OverviewRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_overview': {
      id: '/_overview'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_overview/': {
      id: '/_overview/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof OverviewIndexRouteImport
      parentRoute: typeof OverviewRoute
    }
    '/_overview/staffing': {
      id: '/_overview/staffing'
      path: '/staffing'
      fullPath: '/staffing'
      preLoaderRoute: typeof OverviewStaffingRouteImport
      parentRoute: typeof OverviewRoute
    }
    '/_overview/equipment': {
      id: '/_overview/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof OverviewEquipmentRouteImport
      parentRoute: typeof OverviewRoute
    }
  }
}

interface OverviewRouteChildren {
  OverviewEquipmentRoute: typeof OverviewEquipmentRoute
  OverviewStaffingRoute: typeof OverviewStaffingRoute
  OverviewIndexRoute: typeof OverviewIndexRoute
}

const OverviewRouteChildren: OverviewRouteChildren = {
  OverviewEquipmentRoute: OverviewEquipmentRoute,
  OverviewStaffingRoute: OverviewStaffingRoute,
  OverviewIndexRoute: OverviewIndexRoute,
}

const OverviewRouteWithChildren = OverviewRoute._addFileChildren(
  OverviewRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  OverviewRoute: OverviewRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
